### ISSUE TITLE
Erorr when installing from PIP

### ISSUE THREAD

**Issue by khoroshyy** [hesther/espsim#32]
Hi,
I am getting this error when installing from pip, Any hints how to solve it?
Thanks.

petro@lilla:/mnt/wwn-0x50014ee2b5d8d3a1-part1/remote_files/GDrive/Documents/work/UOCHB/HPCg/Services/kudova/clustrering$
> pip install git+https://github.com/hesther/ehreact.git
Collecting git+https://github.com/hesther/ehreact.git
  Cloning https://github.com/hesther/ehreact.git to /tmp/pip-req-build-guvk_3oy
  Running command git clone --filter=blob:none --quiet https://github.com/hesther/ehreact.git /tmp/pip-req-build-guvk_3oy
  Resolved https://github.com/hesther/ehreact.git to commit 3213324c3310874a1dc66dc553faa924ef5ce212
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-req-build-guvk_3oy/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-guvk_3oy/setup.py", line 30, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-guvk_3oy/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-guvk_3oy/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-guvk_3oy/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by khoroshyy** [comment]
I have fixed it, and added pull request

**Comment by hesther** [comment]
Great thanks! I will have a look later today and merge it than, thank you very much for looking into the problem!
